/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetlang_epoll_EPoll */

#ifndef _Included_org_jetlang_epoll_EPoll
#define _Included_org_jetlang_epoll_EPoll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    select
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jetlang_epoll_EPoll_select
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    getEpollEventIdxAddress
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jetlang_epoll_EPoll_getEpollEventIdxAddress
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    getReadBufferAddress
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jetlang_epoll_EPoll_getReadBufferAddress
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    getMsgLengthAddress
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_jetlang_epoll_EPoll_getMsgLengthAddress
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    init
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_org_jetlang_epoll_EPoll_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    freeNativeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jetlang_epoll_EPoll_freeNativeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    interrupt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jetlang_epoll_EPoll_interrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    clearInterrupt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jetlang_epoll_EPoll_clearInterrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    ctl
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jetlang_epoll_EPoll_ctl
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jetlang_epoll_EPoll
 * Method:    recvmmsg
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jetlang_epoll_EPoll_recvmmsg
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
